### ISSUE TITLE
Kompileringsfel i master

### ISSUE THREAD

**Issue by fribbe** [Forsstrom-HF/HFC#246]
"error: 'PDOPTION_BACKLIGHT_IFSUPP' was not declared"

Beror på att två rader i samband med samband med branch CleanupPropertDisplayParameters felaktigt felaktigt blivit borttagna i master PropertyDisplay.h. Skall vara borttagna i CleanupPropertDisplayParameters.

#define PDOPTION_BACKLIGHT_IFPRIMARY 0x0080
#define PDOPTION_BACKLIGHT_IFSUPP 0x0100

Felet uppstod troligen pga en felaktig lösning härifrån av konflikt i vänster/högerriktning i filen PropertyDisplay.h vid rebase av CleanupPropertyDisplay ovanpå master som gjordes nyss. Skulle troligen behållit master koden men det blev kanske tvärtom.

Problemet försvinner troligen efter merge CleanupPropertyDisplay -> master men rätta sättet är antagligen att undo rebase om det går?

**Comment by alexanderOlssonAtForsstromHF** [comment]
Fixad
